### PR TITLE
fix(ci): add linux script

### PR DESCRIPTION
**Pull request by webdev778**
(#113)

### CODE REVIEW

**Comment by ronaldtse** [comment]
@webdev778 can you also upload the GitHub Action workflow for releasing the Linux build? Thanks.

**Comment by strogonoff** [comment]
Looks good

**Comment by strogonoff** [comment]
> @webdev778 can you also upload the GitHub Action workflow for releasing the Linux build? Thanks.

@ronaldtse I added `ubuntu-latest` to our build matrix (https://github.com/glossarist/glossarist-desktop/blob/master/.github/workflows/release.yml#L15)

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Pull request merged**
